//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingPOM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestingPOM.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedemosite.co.uk/addauser.php.
        /// </summary>
        internal static string ExpectedAddUserHeaderLinkHREF {
            get {
                return ResourceManager.GetString("ExpectedAddUserHeaderLinkHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Add a User.
        /// </summary>
        internal static string ExpectedAddUserHeaderLinkText {
            get {
                return ResourceManager.GetString("ExpectedAddUserHeaderLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedemosite.co.uk/thedatabase.php.
        /// </summary>
        internal static string ExpectedDBHeaderLinkHREF {
            get {
                return ResourceManager.GetString("ExpectedDBHeaderLinkHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. The Database.
        /// </summary>
        internal static string ExpectedDBHeaderLinkText {
            get {
                return ResourceManager.GetString("ExpectedDBHeaderLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedemosite.co.uk/getyourowndbonline.php.
        /// </summary>
        internal static string ExpectedDBOnlineHeaderLinkHREF {
            get {
                return ResourceManager.GetString("ExpectedDBOnlineHeaderLinkHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Get your db online.
        /// </summary>
        internal static string ExpectedDBOnlineHeaderLinkText {
            get {
                return ResourceManager.GetString("ExpectedDBOnlineHeaderLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedemosite.co.uk/index.php.
        /// </summary>
        internal static string ExpectedHomeHeaderLinkHREF {
            get {
                return ResourceManager.GetString("ExpectedHomeHeaderLinkHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Home.
        /// </summary>
        internal static string ExpectedHomeHeaderLinkText {
            get {
                return ResourceManager.GetString("ExpectedHomeHeaderLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Home.
        /// </summary>
        internal static string ExpectedHomepageHeading {
            get {
                return ResourceManager.GetString("ExpectedHomepageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the links above, in sequence, for an example of a username &amp; password login web based system, developed using PHP, JavaScript and a MySQL database..
        /// </summary>
        internal static string ExpectedIntroString1 {
            get {
                return ResourceManager.GetString("ExpectedIntroString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files on this site are generated using a default header and footer using &lt;?php include(&quot;afilename.inc&quot;); ?&gt;  This page you are viewing is generated from the following three files:.
        /// </summary>
        internal static string ExpectedIntroString2 {
            get {
                return ResourceManager.GetString("ExpectedIntroString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedemosite.co.uk/login.php.
        /// </summary>
        internal static string ExpectedLoginHeaderLinkHREF {
            get {
                return ResourceManager.GetString("ExpectedLoginHeaderLinkHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Login.
        /// </summary>
        internal static string ExpectedLoginHeaderLinkText {
            get {
                return ResourceManager.GetString("ExpectedLoginHeaderLinkText", resourceCulture);
            }
        }
    }
}
